DROP TABLE IF EXISTS dashboard_shares;
DROP TABLE IF EXISTS commands;
DROP TABLE IF EXISTS device_keys;
DROP TABLE IF EXISTS telemetry;
DROP TABLE IF EXISTS devices;
DROP TABLE IF EXISTS projects;
DROP EXTENSION IF EXISTS pgcrypto;
DROP EXTENSION IF EXISTS timescaledb;
